craftcms/cloud-extension-yii2

composer.json
src/runtime/Runtime.php
src/runtime/event/CraftCommandEvent.php
src/runtime/event/EventHandler.php

Adds a custom Runtime and EventHandler

Add Runtime and EventHandler to handle multiple events

---

src/Helper.php

We need to check for table existence in our bootstrap, which means we cannot use the normal `\craft\db\Connection::tableExists`, as it relys on the cache component we are trying to configure.
Looking for extra 👀 on the actual query, to see if you spot any issues. I've tested it in mysql and postgres.
@angrybrad are there any potential permissions/multi-tenant issues?

Add tableExists check

---

src/HeaderEnum.php
src/StaticCaching.php
src/web/ResponseBehavior.php

Cache purge tag by host

---

src/templates/fsSettings.html

This was the only reference using this URL, so I switched it over to the main article about asset management.

New URL in filesystem settings

---

src/controllers/AssetsController.php

Set newFolderId instead of folderId

---

src/Helper.php
src/cli/controllers/AssetBundlesController.php

Fail early if ephemeral

---

src/runtime/variables/VariablesLoader.php

Adds simple logging when loading environment variables from a file.

Adds logging when loading variables

---

src/Helper.php
src/Module.php

Fixed a bug where configured log targets were inadvertently being overwritten.

Don't overwrite log targets

---

src/web/AssetManager.php
src/web/assets/rebrand/RebrandAsset.php

Fix rebrand assets

---

src/fs/Fs.php

Fix issues where permissions errors would occur when creating directories

Apply metadata config to FS methods

---

src/StaticCache.php

Adds a missing comma between directives.

Add missing comma

---

src/ImageTransformer.php

Cloudflare's image transformer now supports webp (as well as avif).

Support webp

---

src/cli/controllers/BuildController.php
src/cli/controllers/RunningTimeTrait.php

Log build time

---

src/fs/Fs.php

Fixes env var parsing for Local Filesystem path

Fix env var parsing for local FS path

---

src/cli/controllers/AssetBundlesController.php

Addresses unpublished assets from `DatepickerI18nAsset`.

Fix i18n datepicker

---

src/web/AssetManager.php

Use full path instead of resolving back to alias

---

src/StaticCache.php

Preserve existing Cache-Control, but default to public with max-age.

---

src/fs/AssetsFs.php

`@web` is not recommended and will result in a printed warning.

Use root relative for default web URL.

---

src/StaticCache.php
src/StaticCacheTag.php

Improve tag logging

---

src/Config.php
src/ImageTransformer.php
src/Module.php
src/StaticCache.php
src/controllers/AssetsController.php

Adds `logLevel` config to independently control log level.

Configurable log level

---

composer.json
src/queue/SqsQueue.php

To be released following the release of Craft 4.15.0.
https://github.com/craftcms/cms/pull/16672

Sync releaseAll with SQS queue

---

src/ImageTransformer.php

Fixes https://github.com/craftcms/cloud-extension-yii2/issues/89

Ensure Cloud transformer is only used for Cloud FS
